import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Usage Guidelines | StartupAI Tools",
  description: "Read the StartupAI Tools terms of service. Understand our website guidelines, acceptable usage parameters, and liability exclusions.",
};

export default function TermsPage() {
  return (
    <div className="container section" style={{ maxWidth: '800px', padding: '4rem 1.5rem' }}>
      <h1 style={{ fontSize: 'clamp(2.5rem, 5vw, 3.5rem)', marginBottom: '2rem', fontWeight: 900, letterSpacing: '-0.03em' }}>
        Terms of <span className="text-gradient">Service</span>
      </h1>
      
      <div className="glass-panel" style={{ padding: '3rem', borderRadius: '16px', border: '1px solid var(--border-light)', background: 'var(--bg-card)', lineHeight: '1.75', color: 'var(--text-muted)' }}>
        <p className="text-muted" style={{ marginBottom: '2rem', fontSize: '0.9rem', fontWeight: 600 }}>
          Last Updated: June 5, 2026
        </p>
        
        <p style={{ marginBottom: '1.5rem', fontSize: '1.05rem' }}>
          Welcome to StartupAI Tools (the "Service", "Website"). By accessing, browsing, or using the utility tools, calculators, sitemaps, and content hosted on our site, you agree to comply with and be bound by the following Terms of Service ("Terms"). Please read these terms carefully. If you do not agree to all terms, you must cease using this Website immediately.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          1. Acceptable Use of the Service
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          StartupAI Tools provides free web utilities for personal, educational, and commercial purposes. You agree to use the Service only for lawful intents. You are strictly prohibited from:
        </p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <li>Using automated scripts, bots, scraping tools, or spiders to fetch tool outputs or sitemaps at high volumes, which causes excessive server load.</li>
          <li>Attempting to bypass access controls, execute denial of service attacks, or injecting malicious scripts into our client-side processing utilities.</li>
          <li>Reverse-engineering the underlying JavaScript tool bundles or using our code to build competing utilities that violate intellectual property boundaries.</li>
        </ul>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          2. Intellectual Property and Content Ownership
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          All site designs, code bases, layouts, graphics, custom logos, sitemap scripts, and blog articles are the exclusive property of StartupAI Tools. 
        </p>
        <p style={{ marginBottom: '1.5rem' }}>
          **User-Submitted Input and Output Ownership:** Any text, files, configurations, or images you paste or upload into our tools remain your exclusive intellectual property. StartupAI Tools claims no ownership, copyright, or rights over the output generated by our tools (e.g., generated schema markups, formatted JSON files, or translated articles). You are free to use, distribute, or monetize the generated outputs as you see fit.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          3. Disclaimer of Warranties
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          The tools and resources hosted on StartupAI Tools are provided on an **"AS IS"** and **"AS AVAILABLE"** basis without warranty of any kind, either express or implied. 
        </p>
        <p style={{ marginBottom: '1.5rem' }}>
          While we make every effort to optimize our algorithms, we do not warrant that our outputs (such as grammar check corrections, plagiarism scores, SEO sitemaps, or mathematical metrics) are legally compliant, 100% accurate, or suitable for your specific commercial activities. Use of any generated material is at your own personal risk.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          4. Limitation of Liability
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          To the maximum extent permitted by law, StartupAI Tools, its owners, developers, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from:
        </p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <li>Your use of, or inability to use, the site tools or resources.</li>
          <li>Any errors, bugs, or inaccuracies in the generated output files.</li>
          <li>Temporary service downtime, connection latency, or package bundle failures.</li>
        </ul>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          5. Modifications to Terms
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          We reserve the right to modify these Terms of Service at any time without prior notification. By continuing to use StartupAI Tools after modifications are posted, you agree to be bound by the updated terms. Please check this page periodically.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          6. Governing Law
        </h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of your local jurisdiction, without regard to its conflict of law principles. If you have any inquiries regarding these terms, please contact:
        </p>
        <p style={{ marginTop: '0.5rem', fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-main)' }}>
          terms@startupai.tech
        </p>
      </div>
    </div>
  );
}
