"use client";
import Link from "next/link";

import { useState } from "react";
import { Code, Copy, Check, ArrowLeft } from "lucide-react";

export default function MetaTagGenerator() {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [keywords, setKeywords] = useState("");
  const [author, setAuthor] = useState("");
  const [robots, setRobots] = useState("index, follow");
  
  const [copied, setCopied] = useState(false);

  // Generate the HTML snippet
  const generateMetaTags = () => {
    let tags = [];
    
    if (title) tags.push(`<title>${title}</title>\n<meta name="title" content="${title}">`);
    if (description) tags.push(`<meta name="description" content="${description}">`);
    if (keywords) tags.push(`<meta name="keywords" content="${keywords}">`);
    if (robots) tags.push(`<meta name="robots" content="${robots}">`);
    if (author) tags.push(`<meta name="author" content="${author}">`);
    
    // Add default charset and viewport for good measure
    return `<!-- SEO Meta Tags Generated by StartupAI -->\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n${tags.join("\n")}`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMetaTags());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Check character limits
  const isTitleTooLong = title.length > 60;
  const isDescTooLong = description.length > 160;

  return (
    <div className="container" style={{ padding: '3rem 1.5rem' }}>
      <Link
        href="/tools"
        className="btn btn-outline"
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "0.5rem",
          marginBottom: "1.5rem",
          fontSize: "0.85rem",
          padding: "0.5rem 1rem",
        }}
      >
        <ArrowLeft size={16} /> Back to Tools
      </Link>

      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
          <Code color="var(--primary)" /> Meta Tag Generator
        </h1>
        <p style={{ color: 'var(--text-muted)' }}>Create perfectly optimized SEO meta tags for your HTML documents to rank higher on Google.</p>
      </div>

      <div className="grid-2" style={{ marginBottom: '3rem' }}>
        {/* Form Area */}
        <div className="card">
          <h3 style={{ fontSize: '1.25rem', marginBottom: '1.5rem' }}>Site Information</h3>
          
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
              <label style={{ fontWeight: 600 }}>Site Title</label>
              <span style={{ fontSize: '0.8rem', color: isTitleTooLong ? '#dc2626' : 'var(--text-muted)' }}>
                {title.length} / 60 chars (Recommended)
              </span>
            </div>
            <input 
              type="text" 
              className="input-field" 
              placeholder="e.g. Best SEO Tools Online - Free Generators"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
              <label style={{ fontWeight: 600 }}>Site Description</label>
              <span style={{ fontSize: '0.8rem', color: isDescTooLong ? '#dc2626' : 'var(--text-muted)' }}>
                {description.length} / 160 chars (Recommended)
              </span>
            </div>
            <textarea 
              className="input-field" 
              style={{ minHeight: '100px', resize: 'vertical' }}
              placeholder="A brief summary of your page. This is what shows up under your blue link in Google search results."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          <div style={{ marginBottom: '1.5rem' }}>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 600 }}>Keywords (Comma Separated)</label>
            <input 
              type="text" 
              className="input-field" 
              placeholder="e.g. seo tools, meta generator, tag builder"
              value={keywords}
              onChange={(e) => setKeywords(e.target.value)}
            />
          </div>

          <div className="grid-2" style={{ gap: '1rem', marginBottom: '1rem' }}>
            <div>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 600 }}>Search Engine Robots</label>
              <select 
                className="input-field"
                value={robots}
                onChange={(e) => setRobots(e.target.value)}
                style={{ cursor: 'pointer', background: 'white' }}
              >
                <option value="index, follow">Index, Follow (Recommended)</option>
                <option value="noindex, follow">No Index, Follow</option>
                <option value="index, nofollow">Index, No Follow</option>
                <option value="noindex, nofollow">No Index, No Follow</option>
              </select>
            </div>
            <div>
              <label style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 600 }}>Author (Optional)</label>
              <input 
                type="text" 
                className="input-field" 
                placeholder="e.g. John Doe"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
              />
            </div>
          </div>
        </div>

        {/* Output Area */}
        <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '1.25rem', margin: 0 }}>Generated HTML Tags</h3>
            <button className="btn btn-primary" style={{ padding: '0.4rem 0.75rem', fontSize: '0.8rem' }} onClick={handleCopy} disabled={!title && !description}>
              {copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'Copied!' : 'Copy to Clipboard'}
            </button>
          </div>
          
          <div style={{ flexGrow: 1, background: '#1e293b', color: '#f8fafc', borderRadius: '8px', padding: '1.5rem', overflowX: 'auto', fontFamily: 'monospace', fontSize: '0.9rem', lineHeight: 1.6 }}>
            {(!title && !description) ? (
              <span style={{ color: '#64748b' }}>// Fill out the form to generate your meta tags...</span>
            ) : (
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                {generateMetaTags()}
              </pre>
            )}
          </div>

          <div style={{ marginTop: '1.5rem', padding: '1rem', background: '#eff6ff', borderRadius: '8px', border: '1px solid #bfdbfe' }}>
            <strong style={{ color: '#1e40af', display: 'block', marginBottom: '0.25rem' }}>How to install:</strong>
            <p style={{ color: '#1d4ed8', fontSize: '0.875rem', margin: 0 }}>
              Copy the code block above and paste it inside the <code>&lt;head&gt;</code> section of your HTML document.
            </p>
          </div>
        </div>
      </div>

      {/* SEO Content Section */}
      <div className="prose">
        <h2>What are Meta Tags?</h2>
        <p>If you right-click anywhere on this webpage and select "View Page Source", you will see a bunch of confusing HTML code. Right at the very top of that code, hidden inside the <code>&lt;head&gt;</code> section, are several lines of code called Meta Tags.</p>
        <p>Meta tags are essentially hidden labels. They are completely invisible to a normal human reading the website, but they are incredibly visible to search engine robots (like Googlebot). They provide a neat, structured summary of exactly what your webpage is about so that Google knows exactly how to categorize you in their search results.</p>

        <h2>The anatomy of a perfect Meta Tag setup</h2>
        <p>Not all meta tags are created equal. Some are absolutely critical, while others are essentially ignored by modern search engines. Here is what you need to focus on:</p>

        <h3>1. The Title Tag</h3>
        <p>This is arguably the most important SEO element on your entire page. When you search for something on Google, the massive blue clickable link that you see is pulled directly from the Title Tag. It needs to be catchy, include your main keyword, and ideally sit between 50 and 60 characters. If you make it too long, Google will chop it off and replace the end with an ellipsis (...).</p>

        <h3>2. The Meta Description</h3>
        <p>If the Title Tag is the blue link, the Meta Description is the grey paragraph of text directly underneath it in the search results. While Google has stated that the description doesn't directly influence your rank algorithmically, it massively influences your <strong>Click-Through Rate (CTR)</strong>. It acts as your elevator pitch to convince the searcher to click on your link instead of the competitor below you. Keep it under 160 characters!</p>

        <h3>3. Meta Keywords</h3>
        <p>Back in the late 90s and early 2000s, webmasters would stuff hundreds of keywords into this tag to trick Yahoo and AskJeeves into ranking them #1. Because it was so heavily abused, Google officially announced in 2009 that they completely ignore the keywords tag. However, some smaller, alternative search engines still use it, so it doesn't hurt to include two or three highly relevant terms.</p>

        <h3>4. The Robots Tag</h3>
        <p>This tag gives direct orders to the web scrapers. If you set it to <strong>"index, follow"</strong>, you are telling Google to scan the page, add it to their search results, and follow any links on the page. If you have a private page (like a user dashboard or an admin login), you would change this to <strong>"noindex"</strong> to hide it from the public internet.</p>
      </div>
    </div>
  );
}
