export default function DisclaimerPage() {
  return (
    <div className="container section" style={{ maxWidth: '800px' }}>
      <h1 style={{ fontSize: '3rem', marginBottom: '2rem' }}>Disclaimer</h1>
      <div className="glass-panel" style={{ padding: '3rem' }}>
        <p className="text-muted" style={{ marginBottom: '2rem' }}>Last Updated: {new Date().toLocaleDateString()}</p>
        
        <h3 style={{ marginTop: '2rem', marginBottom: '1rem' }}>1. Educational and Informational Purpose</h3>
        <p style={{ marginBottom: '1rem', lineHeight: '1.6' }}>
          All tools, calculators, generators, and content provided on StartupAI Tools are for educational, informational, and brainstorming purposes only. The information and results generated by our tools do not constitute professional, legal, financial, or technical advice.
        </p>
        
        <h3 style={{ marginTop: '2rem', marginBottom: '1rem' }}>2. No Warranties or Guarantees</h3>
        <p style={{ marginBottom: '1rem', lineHeight: '1.6' }}>
          This website and its tools are provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind, either express or implied. We do not warrant that the tools will be 100% accurate, error-free, uninterrupted, or that any generated results (such as plagiarism scores, word counts, or meta tags) are legally compliant or suitable for your specific circumstances.
        </p>
        
        <h3 style={{ marginTop: '2rem', marginBottom: '1rem' }}>3. Limitation of Liability</h3>
        <p style={{ marginBottom: '1rem', lineHeight: '1.6' }}>
          Under no circumstances shall StartupAI Tools, its owners, developers, or affiliates be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with your access to, use of, or inability to use this website, its tools, or its contents. You use all generated outputs and tools at your own risk.
        </p>
        
        <h3 style={{ marginTop: '2rem', marginBottom: '1rem' }}>4. External Links</h3>
        <p style={{ marginBottom: '1rem', lineHeight: '1.6' }}>
          Our website may contain links to external third-party websites or services. We do not monitor, endorse, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through our site.
        </p>
        
        <h3 style={{ marginTop: '2rem', marginBottom: '1rem' }}>5. User Responsibility</h3>
        <p style={{ lineHeight: '1.6' }}>
          You are solely responsible for verifying the accuracy of any tool results before making decisions or publishing content based on them. It is your responsibility to consult with appropriate professionals before taking any actions based on information generated on this site.
        </p>
      </div>
    </div>
  );
}
