import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Disclaimer - Terms of Accuracy | StartupAI Tools",
  description: "Read the StartupAI Tools disclaimer. Understand our limitations regarding tool accuracy, professional advice, and external links.",
};

export default function DisclaimerPage() {
  return (
    <div className="container section" style={{ maxWidth: '800px', padding: '4rem 1.5rem' }}>
      <h1 style={{ fontSize: 'clamp(2.5rem, 5vw, 3.5rem)', marginBottom: '2rem', fontWeight: 900, letterSpacing: '-0.03em' }}>
        Disclaimer
      </h1>
      
      <div className="glass-panel" style={{ padding: '3rem', borderRadius: '16px', border: '1px solid var(--border-light)', background: 'var(--bg-card)', lineHeight: '1.75', color: 'var(--text-muted)' }}>
        <p className="text-muted" style={{ marginBottom: '2rem', fontSize: '0.9rem', fontWeight: 600 }}>
          Last Updated: June 5, 2026
        </p>
        
        <p style={{ marginBottom: '1.5rem', fontSize: '1.05rem' }}>
          This Legal Disclaimer ("Disclaimer") governs your use of StartupAI Tools ("Website", "Service"). By using any of the online calculators, code formatters, converters, converters, or checkers available on our platform, you acknowledge and agree to all terms of this disclaimer. Please review this page carefully.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          1. Educational and Informational Purposes Only
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          All tools, calculators, sitemaps, templates, and content provided on this Website are for educational, informational, and brainstorming purposes only. The information and results generated by our utilities do not constitute professional, legal, financial, architectural, or technical advice. 
        </p>
        <p style={{ marginBottom: '1.5rem' }}>
          Any output generated (such as plagiarism ratings, word counts, tax estimates, loan EMI schedules, or SEO evaluations) is intended as a helpful guide and should not replace professional consultation.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          2. No Warranties or Guarantees
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          StartupAI Tools is provided on an **"AS IS"** and **"AS AVAILABLE"** basis. While we strive to maintain our algorithms and optimize page speed, we make no warranties, express or implied, regarding:
        </p>
        <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <li>The accuracy, completeness, reliability, or correctness of any tool results or calculations.</li>
          <li>The uptime, availability, or uninterrupted service of the Website.</li>
          <li>The security, safety, or error-free execution of the browser-based client-side scripts.</li>
        </ul>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          3. Specific Tool Disclaimers
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          * **Financial & Calculator Tools:** Results from tools like the Loan Calculator, GST Calculator, or Stripe Fee Calculator are estimates only. Actual tax rates, interests, and transaction fees vary by location and provider. Do not make financial decisions solely based on these estimates.
          * **SEO & Checker Tools:** Outputs from the AdSense Eligibility Checker, Robots.txt Generator, and Sitemap Generator are suggestions. We do not guarantee search engine rankings or AdSense approval.
          * **Content & Plagiarism Tools:** The Plagiarism Checker scans available public resources but may not identify content behind paywalls, private databases, or academic journals.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          4. Limitation of Liability
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          In no event shall StartupAI Tools, its owners, developers, or affiliates be liable for any direct, indirect, incidental, consequential, special, or exemplary damages (including but not limited to loss of traffic, revenue, business interruption, or data corruption) arising out of your use of or inability to use this Website, its tools, or its generated data files.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          5. External Links Disclaimer
        </h2>
        <p style={{ marginBottom: '1.5rem' }}>
          Our Website contains hyperlinks to external third-party websites or APIs (such as dictionary lookups or translation services). We do not monitor, endorse, or assume responsibility for the content, privacy practices, or accuracy of information on these third-party domains.
        </p>

        <h2 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-main)', marginTop: '2rem', marginBottom: '0.85rem' }}>
          6. User Verification Responsibility
        </h2>
        <p>
          Before publishing content, deploying robots/sitemaps to search engines, or submitting tax metrics based on our tool outputs, it is your responsibility to verify the data manually or consult with appropriate legal or financial professionals. If you have questions regarding this disclaimer, please contact us at:
        </p>
        <p style={{ marginTop: '0.5rem', fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-main)' }}>
          disclaimers@startupai.tech
        </p>
      </div>
    </div>
  );
}
